let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Manette XBOX Classic",
    price: 8500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Manette XBOX POP",
    price: 17000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "The last Of Us PART II PS4",
    price: 25000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Call Of Duty Black OPS PC",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Call Of Duty Black OPS PS4",
    price: 25000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Call Of Duty Black OPS XBOX",
    price: 24050,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Oculus gen 3",
    price: 45000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Razer DeathAdder",
    price: 58220,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Logitech G pro",
    price: 45000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Sedatech Gaming Tour I9-9700U",
    price: 750000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "USB-C Mechanical Gaming Keyboard",
    price: 83500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Sennheiser GSP 670 Casque Gaming",
    price: 95000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.jpg",
  },
];
